### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by rladstaetter** [dlemmermann/formsfx#1]
Please add a license file.

**Comment by dlemmermann** [comment]
Looking into this right now. Which one to use? So many options.

**Comment by itaisha** [comment]
I would like to preface this entire message by saying I'm not a lawyer, and this is all based on my own personal understanding. 

This site has a nice succinct comparison of popular open-source licenses (assuming this is meant to be open source):  https://choosealicense.com/licenses/  

Personally, I always prefer projects which use Apache or MIT, as they allow usage in commercial products as well. Since this is Java you can also use GPLv2 + Classpath exception (http://openjdk.java.net/legal/gplv2+ce.html), which basically (to my personal understanding!) means simply including the JAR in the classpath does not force a project using your JAR to also be GPL. This is somewhat similar to LGPL.  

If you want to completely disallow integrating this into commercial projects, your best bet is probably AGPL. This is used by e.g. iText, so programmers can freely use it as long as their project is open source as well, but may purchase a commercial license if they need it (as the owner of the code you may re-issue it under whatever license you like).

**Comment by dlemmermann** [comment]
I have added the Apache 2.0 license.
